### PR TITLE
Validates on instantiation from existing instance.

### LINKED ISSUE #313: Add enums to the structs when enums are in the openapi.yml
See https://dry-rb.org/gems/dry-types/1.0/enum/

Start with file access.  Once complete, this should raise an error:

```ruby
Cocina::Models::FileAccess.new(access: 'citation-only', download: 'none')
```

### PR DESCRIPTION
**Pull request by justinlittman**
closes #313

**NOTE:  Changes to openapi.yml require updating openapi.yml for sdr-api and dor-services-app and generating models - see README.**

## Why was this change made? 🤔
Catch validation problems faster.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit

### CODE REVIEW

File: lib/cocina/generator/schema.rb [hunk 1]
```diff
@@ -67,7 +67,14 @@ def validate
           def self.new(attributes = default_attributes, safe = false, validate = true, &block)
             Validator.validate(self, attributes.with_indifferent_access) if validate && name
             super(attributes, safe, &block)
-                end
+          end
+
+          def new(*args)
```
Comment (jcoyne) [inline lib/cocina/generator/schema.rb:72]: Can we put this code in a module that we include on the model classes?

**Review by jcoyne — CHANGES_REQUESTED** [review]

**Review by jcoyne — APPROVED** [review]
