### PR TITLE
Handle missing value when mapping geo to mods.

### LINKED ISSUE #491: Dry::Struct::MissingAttributeError: Missing attribute: :value
## Backtrace

    line 16 of [PROJECT_ROOT]/app/services/publish/public_desc_metadata_service.rb: doc
    line 106 of [PROJECT_ROOT]/app/services/publish/public_desc_metadata_service.rb: remove_related_item_nodes_for_collections!
    line 97 of [PROJECT_ROOT]/app/services/publish/public_desc_metadata_service.rb: add_collection_reference!

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/50568/faults/86534060)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #491

**NOTE:  Changes to openapi.yml require updating openapi.yml for sdr-api and dor-services-app and generating models - see README.**

## Why was this change made? 🤔
Publishing was failing when mapping to MODs.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit

### CODE REVIEW

File: lib/cocina/models/mapping/to_mods/geographic.rb [hunk 1]
```diff
@@ -70,12 +70,10 @@ def extract_format(geo)
           end
 
           def extract_type(geo)
-            type = geo[:form].find do |form|
-              form[:type].match(TYPE_REGEX) || (form[:type].match(MEDIA_REGEX) && form[:value] == 'Image')
+            type = geo.form.find do |form|
+              form.type.match(TYPE_REGEX) || (form.type.match(MEDIA_REGEX) && form.value == 'Image')
```
Comment (mjgiarlo) [inline lib/cocina/models/mapping/to_mods/geographic.rb:74]: Since we're not using the return value other than as a boolean, can we use `#match?` instead of `#match` here?

**Review by mjgiarlo — APPROVED** [review]
Approve pending consideration of admittedly non-major question

File: lib/cocina/models/mapping/to_mods/geographic.rb (hunk 1 above)
Comment (justinlittman) [reply lib/cocina/models/mapping/to_mods/geographic.rb:74]: Thanks. Fixed.
